### ISSUE TITLE
Wrong parameters when starting glslangValidator

### ISSUE THREAD

**Issue by Kemsekov** [hsimpson/vscode-glsllint#36]
Error:
```
GLSL Lint: Wrong parameters when starting glslangValidator. Arguments: -l --stdin -S -I/{PROJECT_ROOT}/Shaders stderr:
```
where `{PROJECT_ROOT}` is a root of the project.

# Expected behaviour
Works fine and show errors

# Actual behaviour

Failed to start `glslangValidator` because of wrong arguments

# Steps to reproduce

Open any `.glsl` file.

# Environment

OS
 ```Arch linux x64```
code version 
```
1.61.2
6cba118ac49a1b88332f312a8f67186f7f3c1643
x64
```
glslangValidator info 
```
Glslang Version: 10:11.6.0
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 11.6.0
GLSL Version: 4.60 glslang Khronos. 11.6.0
SPIR-V Version 0x00010500, Revision 4
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 10
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100
```

**Comment by hsimpson** [comment]
It looks like the STAGE of the shader could not be determined, in your case the parameter `-S` has no value.
Do you use inline GLSL code or separate file(s)?
Have you checked https://github.com/hsimpson/vscode-glsllint#additionalstageassociations-example about configuring the stages?

Otherwise could you attach a minimal version of your file/project?

**Comment by Kemsekov** [comment]
my bad.. If was just .glsl. When I changed it to .vert it started working fine.

**Comment by Kemsekov** [comment]
Issue solved
