### ISSUE TITLE
Optional stage fallback when stage could not be detected

### ISSUE THREAD

**Issue by hsimpson** [hsimpson/vscode-glsllint#44]
This problem is occurring again for me with .glsl files.
![image](https://user-images.githubusercontent.com/37701550/148110019-9da416a0-0def-41b9-b907-ed0c461f71ea.png)

_Originally posted by @Nolram12345 in https://github.com/hsimpson/vscode-glsllint/issues/3#issuecomment-1005089053_

**Comment by Cazadorro** [comment]
This would be very helpful to me.  It's common, almost standard, to use the .glsl extension *with out any proceeding extension* for library files which are to be included in other files.  ie, `utils.glsl`.  which are then included:

`#include "utils.glsl"`  Right now I have to put .comp in my extension, but that shouldn't be necessary.

**Comment by hsimpson** [comment]
Agreed, but I have to investigate a more smart way, because some one could use `.glsl` also for a fragment, vertex or compute shader. And this is very tricky. 
What is the problem to use the compound extensions like `.comp.glsl`, `.vert.glsl` or `.frag.glsl`? Does this break some other workflow?

My main problem is, that I need to know the stage (`vert`, `frag`, `comp`, others) 100% for sure before sending the shader code to `glslangValidator` binary.

See `glslangValidator --help` for additional Information.

**Comment by Cazadorro** [comment]
> What is the problem to use the compound extensions like .comp.glsl, .vert.glsl or .frag.glsl? Does this break some other workflow?

Yes, because it causes our tools to try to compile them as if they are each of those types of shaders.  They aren't, and thus they fail to compile on our side if we do this.  This is also not something we can fix, other features rely on this happening.

> My main problem is, that I need to know the stage (vert, frag, comp, others) 100% for sure before sending the shader code to glslangValidator binary.

Most of our code in .glsl is not specific to vert, frag, or compute, and is readily used between all of them, so even if you always used compute for this, it would be better than nothing, and work for 90% of our work flow, vs 0% right now.   Alternatively you could run it through  as compute and then as frag, and validate with the one that works, there's very little that's frag specific (quad subgroup access is one common thing), and nothing we've used is vert specific. 

Alternatively again, you could only validate .glsl when it is included in another file, run it as said type of shader.

**Comment by hsimpson** [comment]
Would in your case a configurable fallback to `comp` stage ok? So every shader file which is not a dedicated stage like vert/frag would be used as comp?

**Comment by Cazadorro** [comment]
Yes, comp as default should work for most scenarios scenarios for us.

**Comment by hsimpson** [comment]
> 

So I will implement a configurable fallback stage which is empty per default.
But I won't get around to implementing that until next week.

**Comment by hsimpson** [comment]
I am trying to implement the fallback, but I could not get you shader to lint with `glslangValidator` I have some problems with the `buffer_reference` which looks like is only possible for Vulkan.
Could you test yourself to get the file checked correctly with `glslangValidator` and help me out with the parameters.

**Comment by Cazadorro** [comment]
That file will only work when included in a file with the appropriate extensions enabled (buffer reference 2, all those types, and scalar block layout), so if validated on it's own, it probably won't work.  glslangValidator works with vulkan (infact, is coded against the vulkan GLSL first, then has switches internally to handle other languages), so I'm not sure why vulkan support would be an issue. 

```
#extension GL_EXT_scalar_block_layout: enable
#extension GL_EXT_buffer_reference2 : enable
//for uint64_t etc...
#extension GL_EXT_shader_explicit_arithmetic_types         : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int8    : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int16   : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int32   : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64   : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float32 : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float64 : enable
```

Some of these extensions are only available in vulkan.

**Comment by hsimpson** [comment]
Thanks, I can successfully link your file with a few changes:

- Using the new fallback option (not yet released)
- Enable the specific extensions
- Adding `#version 460` as a the first line
- Adding `-V` as additional args.

I have created a test release, could try this on your side please? If everything works, then I will merge this to into master and release it to the marketplace.
To test this build go to https://github.com/hsimpson/vscode-glsllint/releases/tag/1.8.0-test and download the `vscode-glsllint-1.8.0.vsix` file, then install it manually into VSCode.
After this configure these both options:

```json
"glsllint.glslangValidatorArgs": "-V",
"glsllint.fallBackStage": "comp"
```
In your VSCode settings.
Then restart VSCode and try if your shaders are linting successfully.

**Comment by Cazadorro** [comment]
It appears to work?  We have a few problems though:

* glslc does not require GL_GOOGLE_include_directive, infact if you try to enable it again, glslc fails to work.  There might be an arg for enabling this extension by default but IDK, the workaround would be, for every single file, place a macro that would be conditionally enabled by glslangvalidator.  I don't think this is a good solution, and glslc doesn't work all that different from glslang, and uses it underneath. 

* I can't get glslangValidator to recognize my imports (I don't just use the source location as a include directory), I don't know if it is VSCODE text parsing or what, but even with absolute file paths, I can't seem to get it to just use these other locations.  It is definitely something on the VSCODE end of things, because I can manually enter the command line args just fine, this is what I tried to do:
* `"glsllint.glslangValidatorArgs": "-I\"${env:TEST_WORKSPACE_ENV}/shaderutils/\" -V"`
* This is what worked outside of vscode. `$VULKAN_SDK/Bin/glslangValidator.exe -V -I"$TEST_WORKSPACE_ENV/shaderutils/" example.comp`

* My code however generates depfiles from GLSLC, which means it's actually possible to completely understand the dependency chain from build artifacts, instead of having users manually enter in each file.

**Comment by hsimpson** [comment]
> * Doesn't work `"glsllint.glslangValidatorArgs": "-I\"${env:TEST_WORKSPACE_ENV}/shaderutils/\" -V"`
Unfortunately `"glsllint.glslangValidatorArgs"` does not support `${env:YOUR_ENV}` substitution (could possible another feature, see #48 )

Could you try to use a "full path" for testing?

**Comment by hsimpson** [comment]
@Cazadorro I close this issue here and release the testing version.
